In [1]:
import numpy as np

A = np.array([[2, 3], [1,4]])
determinant = np.linalg.det(A)
print("Determinant: ", determinant)

Determinant:  5.000000000000001


In [2]:
inverse = np.linalg.inv(A)
print("Inverse of A: \n", inverse)

Inverse of A: 
 [[ 0.8 -0.6]
 [-0.2  0.4]]


In [3]:
eigenValues, eigneVectors = np.linalg.eig(A)
print("EigenVal\n", eigenValues)
print("EigenVectors\n", eigneVectors)

EigenVal
 [1. 5.]
EigenVectors
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [4]:
B = np.array([[4, 2], [1, 1]])
eigval, eigvec = np.linalg.eig(B)
print("EigVal: ",eigval)
print("EigVect: \n",eigvec)

EigVal:  [4.56155281 0.43844719]
EigVect: 
 [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


In [ ]:
U, S, Vt = np.linalg.svd(A)
print("U: \n", U)
print("Singular Values: \n", S)
print("V Transpose: \n", Vt)

U: 
 [[-0.65520174 -0.75545395]
 [-0.75545395  0.65520174]]
Singular Values: 
 [5.39834564 0.92620968]
V Transpose: 
 [[-0.38268343 -0.92387953]
 [-0.92387953  0.38268343]]


: 